cvm-version: 0.7.1
cpus: 2
memory: 8192

containers:
  - name: "api-server"
    image: "ghcr.io/tinfoilsh/code-exec-api-server:latest@sha256:be2a4e87a666595143a08fb0da0895788c7a4fad6385f247bb0ea2621196306b"

  - name: "executor"
    image: "ghcr.io/tinfoilsh/code-exec-environment:latest@sha256:a95ccb2ca3d2d900e48e15b17e189564bb0ae74e0eea9e6fb80ff59f0391fab4"

shim:
  upstream-port: 8000
  paths:
    - /exec
    - /read
    - /write
    - /health
